### ISSUE TITLE
[User Story] Fixed location for system tabs

### ISSUE THREAD

**Issue by patrickjaigner** [iterize/tenta#28]
As a system operator, I want to find the Activity, Plots, Config, Data, and Logs tabs at the same location on the website so that I can quickly swap between them without searching for the current location at the left system list interface.

<img width="657" alt="image" src="https://github.com/iterize/tenta/assets/59452158/900b4a52-94a3-4de1-af28-c6fbd9299464">

**Comment by dostuffthatmatters** [comment]
Thank you for the feedback!

Tracked in #40
