### ISSUE TITLE
[User Story] Hide system from system list

### ISSUE THREAD

**Issue by patrickjaigner** [iterize/tenta#33]
As a system operator, I want to hide sensors, such as "Test-Sensor, Moritz Macbook Pro 14," from the sensor list so that I can better focus on the system in operation.

**Comment by empicano** [comment]
Would the option to delete a system (together with its data) from the database achieve the same for you? It's 100% clear what this action does, and is something I wanted to implement anyways.

**Comment by patrickjaigner** [comment]
I was also thinking about it. But there might be use cases where the system is in maintenance or repair for a more extended period (i.e., multiple weeks), and you want to hide the system for the network operator to reduce overhead in monitoring.

Being able to delete sensors from the network is definitely needed. But I guess this would create another user story.

**Comment by dostuffthatmatters** [comment]
Thank you for the feedback!

Tracked in #41
