### ISSUE TITLE
[Bug] Deployment of dashboard does not work as described

### ISSUE THREAD

**Issue by patrickjaigner** [iterize/tenta#39]
Following the instructions to deploy the dashboard ([here](https://tenta.onrender.com/deployment)) did not result in an operational deployment. 

Functional:
- Log In Page
- Network Overview Page
Not Functional:
- Forwarding to Systems Overview Page
- Accessing Systems Overview Page

After exchanging with @dostuffthatmatters I learned that static hosting is not working for the current implementation. He proposed hosting via fly.io providing a fly.toml, which I couldn't get work yet.

It would be helpful to update the documentation.

**Comment by dostuffthatmatters** [comment]
Yes, the documentation states, the dashboard can be hosted as a static site. But NextJS removed the feature of building dynamic routes as static pages, hence it requires a server in the back.

Hosting options are https://fly.io/, https://vercel.com/ or https://render.com/. I will update the documentation on that soon.
